# Use Ubuntu as the base image
FROM ubuntu:latest

# Update package lists and install essential packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    curl

# Symlink python3 to python (optional)
RUN ln -s /usr/bin/python3 /usr/bin/python


# Install Node.js (adjust version as needed)
RUN apt-get update
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get install nodejs -y

#postgres
RUN apt install postgresql
RUN systemctl start postgresql

###################CREATE A USER IN POSTGRES AUTOMATICALLY AND GIVE IT PRIVILEDGE OVER THE DATABASES

# Install npx globally (if needed)
RUN npm install -g npx

# Set working directory
WORKDIR /HomeCosina

# Copy your application files into the container
COPY . /HomeCosina

# Set any other configurations or commands you need here
# For example:
# RUN npm install
# CMD ["npm", "start"]